import logger from '@config/logger';

import { RegisterRoutes } from '@src/routes';

import cors from 'cors';
import express, { Express, json, Request, Response, urlencoded } from 'express';
import helmet from 'helmet';
import swagger from 'swagger-ui-express';

export const app: Express = express();

// Middlewares
app.use(helmet());
app.use(cors());
app.use(urlencoded({ extended: true }));
app.use(json());

// Logger
app.use((req: Request, _res: Response, next) => {
  logger.info(`${req.method} ${req.url}`);
  next();
});

// Swagger UI
app.use('/api/docs', swagger.serve, async (_req: Request, res: Response) => {
  return res.send(swagger.generateHTML(await import('../dist/swagger.json')));
});

app.get('/', (_req: Request, res: Response) => res.redirect('/api/docs'));

// Register routes generated by TSOA
RegisterRoutes(app);
